-- MySQL Script generated by MySQL Workbench
-- Mon Jul 19 16:11:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reactproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `reactproject`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reactproject`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `iduser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reactproject`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reactproject`.`link` (
  `idLink` INT NOT NULL AUTO_INCREMENT,
  `originLink` VARCHAR(400) NULL,
  `customLink` VARCHAR(45) NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idLink`, `user_idUser`),
  UNIQUE INDEX `idlink_UNIQUE` (`idLink` ASC),
  INDEX `fk_link_user_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_link_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `reactproject`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
